// <auto-generated />
using System;
using MatrimonialApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MatrimonialApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502132226_AddPaymentVerification")]
    partial class AddPaymentVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatrimonialApi.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("AdminId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_AdminId");

                    b.HasIndex("EntityId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MatrimonialApi.Models.ContactUnlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UnlockedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileUserId", "UnlockedAt")
                        .HasDatabaseName("IX_ContactUnlocks_Profile");

                    b.HasIndex("UnlockedByUserId", "ProfileUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactUnlocks_Pair");

                    b.HasIndex("UnlockedByUserId", "UnlockedAt")
                        .HasDatabaseName("IX_ContactUnlocks_Unlocker");

                    b.ToTable("ContactUnlocks");
                });

            modelBuilder.Entity("MatrimonialApi.Models.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailVerificationTokens_Hash");

                    b.HasIndex("UserId", "UsedAt", "ExpiresAt")
                        .HasDatabaseName("IX_EmailVerificationTokens_User");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("MatrimonialApi.Models.InterestRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SenderId", "ReceiverId")
                        .HasDatabaseName("IX_InterestRequests_Pair");

                    b.HasIndex("ReceiverId", "Status", "SentAt")
                        .HasDatabaseName("IX_InterestRequests_Received");

                    b.HasIndex("SenderId", "Status", "SentAt")
                        .HasDatabaseName("IX_InterestRequests_Sent");

                    b.ToTable("InterestRequests");
                });

            modelBuilder.Entity("MatrimonialApi.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Notifications_User");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_Notifications_Unread");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MatrimonialApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountBdt")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Orders_Status");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Orders_User");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MatrimonialApi.Models.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountBdt")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GatewayName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GatewayTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentAttempts_TxnId")
                        .HasFilter("\"GatewayTransactionId\" IS NOT NULL");

                    b.HasIndex("OrderId", "AttemptedAt")
                        .HasDatabaseName("IX_PaymentAttempts_Order");

                    b.HasIndex("Status", "AttemptedAt")
                        .HasDatabaseName("IX_PaymentAttempts_Status");

                    b.HasIndex("UserId", "AttemptedAt")
                        .HasDatabaseName("IX_PaymentAttempts_User");

                    b.ToTable("PaymentAttempts");
                });

            modelBuilder.Entity("MatrimonialApi.Models.ProfileIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("AgeYears")
                        .HasColumnType("integer");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("integer");

                    b.Property<string>("CountryOfResidence")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("District")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Division")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("EducationLevelOrder")
                        .HasColumnType("integer");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("ProfileVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Religion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgeYears")
                        .HasDatabaseName("IX_ProfileIndex_Age");

                    b.HasIndex("EducationLevelOrder")
                        .HasDatabaseName("IX_ProfileIndex_EducationOrder");

                    b.HasIndex("HeightCm")
                        .HasDatabaseName("IX_ProfileIndex_Height");

                    b.HasIndex("LastActiveAt")
                        .HasDatabaseName("IX_ProfileIndex_LastActive");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_ProfileIndex_UpdatedAt");

                    b.HasIndex("CountryOfResidence", "Division", "District")
                        .HasDatabaseName("IX_ProfileIndex_Location");

                    b.HasIndex("Status", "ProfileVisible", "Gender", "Religion")
                        .HasDatabaseName("IX_ProfileIndex_Search_Core");

                    b.ToTable("ProfileIndexes");
                });

            modelBuilder.Entity("MatrimonialApi.Models.ProfileReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ReportedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserId", "Status")
                        .HasDatabaseName("IX_ProfileReports_Reported");

                    b.HasIndex("ReporterId", "ReportedUserId")
                        .HasDatabaseName("IX_ProfileReports_Reporter");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_ProfileReports_Status");

                    b.ToTable("ProfileReports");
                });

            modelBuilder.Entity("MatrimonialApi.Models.ProfileView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ViewedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ViewerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ViewedUserId", "ViewedAt")
                        .HasDatabaseName("IX_ProfileViews_ViewedUser");

                    b.HasIndex("ViewerUserId", "ViewedUserId", "ViewedAt")
                        .HasDatabaseName("IX_ProfileViews_ViewerViewed");

                    b.ToTable("ProfileViews");
                });

            modelBuilder.Entity("MatrimonialApi.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MatrimonialApi.Models.SavedProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SavedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SavedUserId");

                    b.HasIndex("UserId", "SavedAt")
                        .HasDatabaseName("IX_SavedProfiles_User");

                    b.HasIndex("UserId", "SavedUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_SavedProfiles_Unique");

                    b.ToTable("SavedProfiles");
                });

            modelBuilder.Entity("MatrimonialApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MatrimonialApi.Models.UserMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Plan")
                        .HasDatabaseName("IX_UserMemberships_Plan");

                    b.ToTable("UserMemberships");
                });

            modelBuilder.Entity("MatrimonialApi.Models.ContactUnlock", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "ProfileUser")
                        .WithMany()
                        .HasForeignKey("ProfileUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatrimonialApi.Models.User", "UnlockedByUser")
                        .WithMany()
                        .HasForeignKey("UnlockedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfileUser");

                    b.Navigation("UnlockedByUser");
                });

            modelBuilder.Entity("MatrimonialApi.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatrimonialApi.Models.InterestRequest", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatrimonialApi.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MatrimonialApi.Models.Notification", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatrimonialApi.Models.Order", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatrimonialApi.Models.PaymentAttempt", b =>
                {
                    b.HasOne("MatrimonialApi.Models.Order", "Order")
                        .WithMany("PaymentAttempts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MatrimonialApi.Models.ProfileIndex", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MatrimonialApi.Models.ProfileIndex", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatrimonialApi.Models.ProfileReport", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatrimonialApi.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("MatrimonialApi.Models.ProfileView", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "ViewedUser")
                        .WithMany()
                        .HasForeignKey("ViewedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatrimonialApi.Models.User", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ViewedUser");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("MatrimonialApi.Models.RefreshToken", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatrimonialApi.Models.SavedProfile", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "SavedUser")
                        .WithMany()
                        .HasForeignKey("SavedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatrimonialApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatrimonialApi.Models.UserMembership", b =>
                {
                    b.HasOne("MatrimonialApi.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("MatrimonialApi.Models.UserMembership", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatrimonialApi.Models.Order", b =>
                {
                    b.Navigation("PaymentAttempts");
                });

            modelBuilder.Entity("MatrimonialApi.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
